apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- application.yaml
- deployment.yaml
- service.yaml

namespace: goapp
images:
- name: goapp
  newName: lucasgalo/goapp
  newTag: ea7bf04d8853e73ab6d3c2f7384b0fb16e7033e2
