name: CD
on:
  push:    
    tags:
      - '*'
jobs:
  build:
    name: Build_Push
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
## push image for to DockerHub
      - name: build image and push to docker hub
        uses: docker/build-push-action@v1.1.0
        with:
          username: galo_pc@outlook.com
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: lucasgalo/goapp
          tags: ${{ github.ref_name }}, latest