name: CD
on:
  push:    
    tags:
      - '*'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
## push image for to DockerHub
      - name: build image and push to docker hub
        uses: docker/build-push-action@v1.1.0
        with:
          username: galo_pc@outlook.com
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: lucasgalo/goapp
          tags: ${{ github.ref_name }}, latest
## Job for Deployment new image
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize_version: v3.6.1
      
      - name: update k8s
        run: |
          cd k8s
          kustomize edit set image goapp=lucasgalo/goapp:${{ github.ref_name }}
          cat kustomization.yaml

      - name: commit
        run: |
          git pull origin main
          git config --local user.email "action@github.com"
          git config --local user.name "Deploy action"
          git commit -am "change image tag"
## Push to the repository itself
      - name: push
        uses: ad-m/github-push-action@master